# Generated by Django 5.0.2 on 2026-01-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_app', '0002_doctor_provider_doctor_providers_recommended_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday')], max_length=200, null=True)),
                ('visit_num', models.PositiveIntegerField(default=2)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_schedule', to='doctor_app.provider')),
                ('working_days', models.ManyToManyField(to='schedule_app.workday')),
            ],
        ),
    ]
