# Generated by Django 5.0.2 on 2026-01-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_doctor_provider_doctor_providers_recommended_service_and_more'),
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='visit_num',
        ),
        migrations.AddField(
            model_name='workday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='provider_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_workday', to='doctor_app.provider'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('workday_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workhour_workday', to='schedule_app.workday')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
