# Generated by Django 5.0.2 on 2026-01-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_remove_workday_end_hour_remove_workday_start_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='duration_min',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
