# Generated by Django 5.0.2 on 2026-02-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('book_app', '0001_initial'),
        ('doctor_app', '0005_remove_provider_service_related_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='strat_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to='account_app.account'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('provider_related', 'date', 'start_time', 'end_time')},
        ),
    ]
