# Generated by Django 5.0.2 on 2026-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0002_remove_account_is_doctor_account_role_account_status"),
        ("book_app", "0002_rename_strat_time_appointment_start_time_and_more"),
        ("doctor_app", "0010_providerreview"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_canceled", False)),
                fields=("provider_related", "date", "start_time", "end_time"),
                name="unique_active_appointment",
            ),
        ),
    ]
