# Generated by Django 5.0.2 on 2026-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_doctor',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('patient', 'patient'), ('doctor_pending', 'doctor_pending'), ('doctor', 'doctor'), ('center_pending', 'center_pending'), ('center_manager', 'center_manager'), ('admin', 'admin')], default='patient', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('pending_review', 'pending_review'), ('active', 'active'), ('rejected', 'rejected'), ('suspended', 'suspended')], default='pending', max_length=20),
        ),
    ]
