# Generated by Django 5.0.2 on 2026-01-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubExpertize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expertize_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertize_sub', to='doctor_app.expertize')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('organizationID', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('phone2', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('account_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_detail', to='account_app.account')),
                ('doctors_recommended', models.ManyToManyField(null=True, related_name='doctors_recommended', to='account_app.account')),
                ('expertize_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertize_doctor', to='doctor_app.expertize')),
                ('subExpertize_relateds', models.ManyToManyField(null=True, related_name='subexpertize_doctor', to='doctor_app.subexpertize')),
            ],
        ),
    ]
