# Generated by Django 5.0.2 on 2026-01-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('organizationID', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('phone2', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('account_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_doctor', to='account_app.account')),
                ('expertize_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertize_doctor', to='doctor_app.expertize')),
                ('subExpertize_relateds', models.ManyToManyField(null=True, related_name='subexpertize_doctor', to='doctor_app.subexpertize')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_provider', models.CharField(blank=True, choices=[('doctor', 'doctor'), ('service', 'service')], default='doctor', max_length=200, null=True)),
                ('doctor_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_provider', to='doctor_app.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='providers_recommended',
            field=models.ManyToManyField(null=True, related_name='providers_recommended', to='doctor_app.provider'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('organizationID', models.CharField(blank=True, max_length=200, null=True)),
                ('phone1', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('phone2', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_manager_account', to='account_app.account')),
                ('providers_recommended', models.ManyToManyField(null=True, to='doctor_app.provider')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='service_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='doctor_app.service'),
        ),
        migrations.DeleteModel(
            name='DoctorDetail',
        ),
    ]
