# Generated by Django 5.0.2 on 2026-01-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('doctor_app', '0002_doctor_provider_doctor_providers_recommended_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='service_related',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='doctor_related',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='type_provider',
        ),
        migrations.AddField(
            model_name='doctor',
            name='provider_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_doctor', to='doctor_app.provider'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('organizationID', models.CharField(blank=True, max_length=200, null=True)),
                ('phone1', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('phone2', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Center_manager_account', to='account_app.account')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='Center_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Center_provider', to='doctor_app.center'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
