# Generated by Django 5.0.2 on 2026-01-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_remove_provider_service_related_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_min', models.PositiveIntegerField(default=10)),
                ('descripton', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='service_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_service', to='doctor_app.medicalservice'),
        ),
    ]
