# Generated by Django 5.0.2 on 2026-01-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0004_medicalservice_provider_service_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='service_related',
        ),
        migrations.DeleteModel(
            name='MedicalService',
        ),
    ]
