# Generated by Django 5.0.2 on 2026-02-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('doctor_app', '0005_remove_provider_service_related_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='account_related',
        ),
        migrations.AddField(
            model_name='provider',
            name='account_related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.account'),
        ),
    ]
