# Generated by Django 5.0.2 on 2026-02-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('doctor_app', '0006_remove_doctor_account_related_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='provider_related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_doctor', to='doctor_app.provider'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='account_related',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_app.account'),
        ),
    ]
