# Generated by Django 5.0.2 on 2026-02-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('doctor_app', '0007_alter_doctor_provider_related_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_requested', models.CharField(choices=[('doctor', 'doctor'), ('center', 'center')], max_length=20)),
                ('documents', models.FileField(upload_to='provider_documents/')),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('account_related', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_app.account')),
            ],
        ),
    ]
