# Generated by Django 5.0.2 on 2026-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0008_providerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
