# Generated by Django 5.0.2 on 2026-02-19 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_remove_account_is_doctor_account_role_account_status'),
        ('doctor_app', '0009_providerapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=1)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('patient_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_review', to='account_app.account')),
                ('provider_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_review', to='doctor_app.provider')),
            ],
        ),
    ]
