# Generated by Django 5.0.2 on 2026-06-01 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_remove_account_is_doctor_account_role_account_status'),
        ('doctor_app', '0011_alter_providerreview_patient_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerreview',
            name='patient_related',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_review', to='account_app.account'),
        ),
    ]
