# Generated by Django 5.0.2 on 2026-06-02 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_remove_account_is_doctor_account_role_account_status'),
        ('doctor_app', '0012_alter_providerreview_patient_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerapplication',
            name='account_related',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.account'),
        ),
    ]
